framework:
    cache:
        # Unique name of your app: used to compute stable namespaces for cache keys.
        prefix_seed: ghentcdh/evwrit

        pools:
            cache.keycloak_tokens:
                adapter: cache.adapter.filesystem
                default_lifetime: 300 # 5 minutes
